---
include:
  - board: seeeduino_xiao_ble
    shield: Solstice_L rgbled_adapter dya_oled_status
    snippet: zmk-usb-logging studio-rpc-usb-uart Solstice_US
    artifact-name: Solstice_L_US

  - board: seeeduino_xiao_ble
    shield: Solstice_R rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart Solstice_US Solstice_R_Offset
    artifact-name: Solstice_R_US

  - board: seeeduino_xiao_ble
    shield: Solstice_L rgbled_adapter dya_oled_status
    snippet: zmk-usb-logging studio-rpc-usb-uart Solstice_JIS
    artifact-name: Solstice_L_JIS

  - board: seeeduino_xiao_ble
    shield: Solstice_R rgbled_adapter
    snippet: zmk-usb-logging studio-rpc-usb-uart Solstice_JIS Solstice_R_Offset
    artifact-name: Solstice_R_JIS

  - board: seeeduino_xiao_ble
    shield: settings_reset
    
